### ISSUE TITLE
Doing /aspet doesn't do anything...

### ISSUE THREAD

**Issue by cpkOfficial** [Kyzderp/ArmorStandPetWiki#3]
Well i guess i just bought a broken plugin? I do /aspet and it just shows "/aspet help"...
Did i just get scammed?

**Comment by Kyzderp** [comment]
And what happens when you do "/aspet help"? The plugin is currently working on my server. Please provide your server version, screenshots of the error, and any other information to help diagnose the issue.

**Comment by Kyzderp** [comment]
Resolved, old deprecated code. Now updated for 1.12.
